### PR TITLE
Add support Ntag21x magic uid

### PR DESCRIPTION
**Pull request by ca1e**
check pwd like a magic uid card if uidMode is true

### CODE REVIEW

**Comment by iceman1001** [comment]
maybe some documentation to how it is going to work?

**Comment by ca1e** [comment]
> maybe some documentation to how it is going to work?

sure, which doc should I edit?

**Comment by ca1e** [comment]
I just modified the [wiki](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Terminal-Commands#uidmode) to add docs for magic uidmode.forgive my poor english you can change it for more humanreadable

**Comment by iceman1001** [comment]
good enough,  thanks!

**Pull request merged**
