### PR TITLE
Add new button action (toggle readonly)

### PR DESCRIPTION
**Pull request by stek29**

### CODE REVIEW

**Comment by iceman1001** [comment]
What should button action "readonly" do?

**Comment by stek29** [comment]
@iceman1001 Enable read-only mode, just as the name suggests.
From what I see in source, enabling readonly mode makes chameleon ignore all write requests, which might be useful for easy replay attack -- instead of having to restore original content manually, you can just enable readonly mode.

However, I haven't tested this change yet -- I didn't have my NFC toolset with me when testing, I only had chameleon.

**Comment by iceman1001** [comment]
So read-only mode should  emulate which card type?  and it should disable all write functionality in that specific protocol?

**Comment by stek29** [comment]
@iceman1001 readonly mode already exists and it's been there for quite a long time -- but it only was settable via console. I've just added button action to do that without computer connected to chameleon.

**Review by iceman1001 — APPROVED** [review]

**Comment by iceman1001** [comment]
You are correct,  I never used that command.  I had to look it up.   I'll merge it!

**Pull request merged**
