### PR TITLE
Mifare Clean

### LINKED ISSUE #161: [REQ] Mifare Classic S0/B0 should be readable without any authentication
### Description
The Block 0 in Sector 0 of any Mifare Classic emulated memory should be readable without any authentication, as expected by some readers, and implied by specs.

### Interest
This may fix some inconsistency with some readers, like MCT notably, and may be expected by some readers anyway.

### Possible implementation
Not sure if necessary to and how to "skip" the authenticating phase, as not sure how the readers would try to read S0/B0 without any auth. I see two possible behaviours: expecting any auth attempt to success if access to S0/B0 is requested, or not trying to auth at all and issuing a READ operation directly:
- S0/B0 access is requested by an AUTH operation in "ACTIVE" state: the application should directly jump to "AUTHED_IDLE" and set a bool to register the direct jump, to then only allow READ operation on S0/B0 in "AUTHED_IDLE";
- a "READ" command on S0/B0 is issued directly before any authentication attempt, and patched in "ACTIVE" state. The application should run the READ logic on S0/B0.

### PR DESCRIPTION
**Pull request by securechicken**
Factored Mifare code more (mostly anticol, authentication and DETECTION code), ensured all MF1S50YYX_V1 anticol and HALT methods are implemented (this notably fixes #161), and fixed DETECTION bugs.
This results in a smaller code (3% on my side, with AVR-GCC 8 and 9), more reactive Mifare simulation (notably on Android MFC), and DETECTION working (again ?).
To be tested with recents serial and DETECTION fixes in GUI (or DETECTION may give expected results in GUI).

### CODE REVIEW

**Comment by iceman1001** [comment]
Excellent as ever!

@bogiton  you have time to take a look?  Or we just merge it?

**Comment by bogiton** [comment]
I don't have any real MFC reader near me, but I could definitely test it with Android. Will let you know in a while.

**Comment by iceman1001** [comment]
I pushed out the v1.2.1.3 GUI which has the detection fixes.

I will merge this one,  and we let the community test :)

**Comment by bogiton** [comment]
Sadly, I think it responds a bit worse than before with TagInfo, at least in my Android phone. Experience was like that:

cham

**Comment by securechicken** [comment]
Well Android phones NFC readers are a pain. I did not know NXP TagInfo on Android, but gave it a try as you mentioned it, and on my case it works even better than MFC (very quick detection, and full read on 4k tags when default factory key are used on sectors). Test phone is a Huawei P10. I also tested with Samsung Galaxy S8, and it's more painful: you really have to find the good spot, which may vary depending on software you use (and basically anything that can change in a millisecond, like... a millisecond), because it would be too easy otherwise.

**Comment by bogiton** [comment]
To be honest I didn't try 4K, only 1K and had the above result. What you say about the good spot and orientation is true. I was struggling to get Chameleon in a good position :P
MCT on the other hand worked better in terms of identifying the tag but the reading was way too slow. Not sure why.
I still want to try out the UL enhancements you did on a real reader to see what we get.

**Pull request merged**
