### PR TITLE
Rewrite flash and memory management codes

### PR DESCRIPTION
**Pull request by securechicken**
Rewritten memory and (SPI) flash management layers:
- to allow automatic and full SPI flash chips detection and capacity usage (available SPI flash memory was arbitrarily constrained to 4Kb + 7*1Kb for now, but as we have seen with SPI_FLASHINFO, the minimum memory capacity we found is 512Kb... what a waste!), and deterministic application/slot memory mapping on it. Doing so, the ChameleonMini would now transparently and fully drive any Adesto AT45DB0x1(E)-like chips, whatever their size from 4 to 64Mbits;
- to allow each application/slot (whatever you want to call them) to use up to all available SPI flash memory divided by number of slots. This opens door to logging, sniffing, and MF Classic 4K emulation in all slots;
- to speed and rationalise read/erase operations on SPI Flash. Unfortunately, could not speed up writing as it appears SPI flash chips we have are like a buggy or constrained version without some Adesto atomic commands found in datasheets;
- to introduce a "CLEARALL" command, that will truly reset and erase all persistent memories at once quicker than CLEAR each slot individually;
- to correct a lot of possible memory overlap/overflow scenarios in memory related codebase and functions. This rewritten memory API simply does not allow any inconsistent memory mapping from applications, and slots overwriting memory space that is dedicated to another;
- to easily allow writing in a slot/application-dedicated memory space, whatever the active slot;
- to ease memory management code reading, and to better separate chip/hardware-based code (SPI Flash or EEPROM) from "application-targeted" memory mapping;
- to allow "SPI_FLASHINFO" showing how much available EEPROM and SPI Flash memory are available per slot.

Passing by:
- moved "SPI_FLASHINFO" to "MEMORYINFO", and added a "MEMORYTEST" command. Moved both to "define" macro enabled codebases, as they would not be necessary except for debugging purposes now;
- ensured "CLEAR" and "CLEARALL" consistency with defaults in Makefile, made them also reset BUTTON states, make CLOSED the default configuration, and ensure CLOSED slots do not require unnecessary memory;
- cleaned some unused spaces and includes in files that were affected by memory management changes;
- having been provided an AVRISPmkII because such a massive and "low-level" rework was not possible with eased flashing and testing workflows, tuned Makefile so that unlocked-bootloader flashing now does not skip dfu-programmer memory validation (because I discovered with unlocked boot loader, there are no memory sections overlaps, so no validation errors).

Tested with unit-level testing on memory read/write/erase operations, and ensured basic-level non regression tests for Mifare application (reading with MFC, and SCL3711). Would welcome anymore real-case scenario testing to further guarantee non-regression.

### CODE REVIEW

**Comment by iceman1001** [comment]
Impressive!

**Comment by iceman1001** [comment]
When this one merges, the GUI need to adapt for spi_info etc...

**Comment by securechicken** [comment]
> When this one merges, the GUI need to adapt for spi_info etc...

@iceman1001 the GUI could adapt to allow each slot being set as MF_4K. It is not mandatory however, as command line on serial already will allow that automatically. Apart from that, nothing is necessary: commands in GUI are generated from firmware commands list, so SPI_WHATEVER being renamed or disabled with a compile flag will not have any effect. A Wiki modification is necessary here and there however (to remove limit on 4k in 1st slot, and to rename SPI_ on Wiki commands list). I'll deal with Wiki.

**Comment by securechicken** [comment]
Force-pushed a rebase to current master, in order to integrate others merged PR.

**Comment by securechicken** [comment]
@iceman1001 also noted in GUI that: 
- the serial timeout is not long enough to let the "CLEARALL" command ends properly. I could make the "CLEARALL" command not waiting the SPI Flash memory to be ready before returning (as I initially did), but this may introduce delays in subsequent flash memory operations because SPI Flash is still being deleted, so think it would be dangerous. This does not alter the command function, but the result is that GUI hangs out and reset when running "CLEARALL", where it could just wait a bit longer for the command to end. A "semaphore" (according to the I/O error message I get then) timeout should certainly be added more milliseconds.
- the GUI is apparently having it's own modifications to configuration/slots when clicking "CLEAR", that are not consistent with the serial-run command. I for instance get a randomly generated UID on 1st or last slot, and a BUTTON_LONG actions set that is not based on the default defined one in Makefile. The GUI should not set anything for slots/settings/configuration when running "CLEAR", and should just refresh all slots reading at the end of operation. The firmware now properly and fully handle "CLEAR"-type operations by clearing memory, and resetting slots to their default configuration, including buttons states.

**Comment by iceman1001** [comment]
I have too little to look into this,  its better to merge and see what happens :)
@bogiton and @Shinhub,   I depend on you to keep track of this.
Hopefully the chameleon RevE rebooted now is working well again.

**Comment by securechicken** [comment]
@iceman1001 well there ARE bits to change in rebootedGUI. Not so much (I would say 3 to 4 vars. init to change, + maybe another condition to add), but still... I do not know sh*t about rebootedGUI for now, so cannot integrate that in no time.

**Comment by iceman1001** [comment]
lets hope Bogiton has time :)  or if someone else feels like contributing :)

**Comment by securechicken** [comment]
Well I started @iceman1001, but this is messy code to start with! Happy it is at least quite monologic, so everything in the same file.

**Comment by iceman1001** [comment]
Thanks for the compliment. *not*

**Comment by securechicken** [comment]
@iceman1001 there IS a compliment. You made it monolithic. The rest is that it is C#, .NET and so on, trying to keep it sync with command-line terminal based software... how clear and simple would you expect the result to be : )

**Comment by iceman1001** [comment]
I was just messing with you.  The all code in one file sucks. haha,  both I and @bogiton  has commented it and we even tried to start with user controls.  Then ppl started commit stuff and atleast I gave up.  A complete rewrite could be in order.   Anyway,  wrong place to discuss GUI.

**Comment by bogiton** [comment]
Can't seem to be able to keep up with @shinhub.. Before I have even read your comments, he already have fixed the GUI. He is unstoppable! :P

**Comment by securechicken** [comment]
@bogiton I work in the nuclear industry. I tend not to let flaws open too much time, you know...
Kidding. It's just that it appeared "theoretically" easy to integrate that, with "theoretically" easy  language/libs, in a "theoretically" cool IDE. I had to try before I forget what had to be done, but I did not quite like it however, so feel free to check if I did not mess with it.

**Comment by securechicken** [comment]
@bogiton @iceman1001 by the way, it seems a lot of Mifare has been fixed, Ultralight and 7b UID are now in, and we bet for better consistency, stability and capabilities with other fixes and memory rework, so to me if there are no big issues to be fixed next week, this would deserve "1.4" release.

**Comment by bogiton** [comment]
@shinhub You are doing a great work, keep up! :)
I'm gonna try with the real Mifare Classic reader during the week, that it wasn't working before, and let you know.

**Comment by maxieds** [comment]
I have been away from the discussion board for a while. Are there any new
features or corrections for the Reve boards that need to be made with the
recent firmware to keep the Chameleon Mini Live Debugger Android app
functional for users? Please respond with as detailed a list as you need to
get all of these great new improvements registered for users on a Droid.

Maxie

**Comment by securechicken** [comment]
@maxieds would be hard to tell depending on where you left and what you do but mainly from user side, we can now set any slot to any application configuration, there are more possible application configurations (on Ultralight and Classic), "SPI_FLASHINFO" is renamed to "MEMORYINFO" and not enabled by default, and finally firmware name contains the commit version at the end of version string.

**Comment by iceman1001** [comment]
@shinhub   Open a new issue "release v1.4" ,  and it should fix  MF_DETECTION,  then we do a release.
Problem we have with releases/tags,  is the CI configuration pushes everything as a release.  Which makes for easy testing (no need to compile)  but messes up a nice release page.
That should be sorted somehow.

@maxieds ,  asking for a detailed list?  As we need to get all of these registred on a droid?  
We lack a changelog file.  In the meantime I suggest reading the release notes on offical releases.. (not the CI releases ...)

Since there is no forum,  the only discussions tends to be in PR's / issues.    @bogiton  and I tried to maintain a certain level of keeping that clean.  ie,  make a new issue for questions etc and label it correct.    This seems to have fallen and we must become better at it.   This will not do.  We all to blame for it.

**Comment by maxieds** [comment]
@iceman
By the same token, if anything new shoes up in the firmware that doesn't,
but should work in my app, please alert me to the problem. I haven't
received any new user reports of errors with your firmware and do not
update my old hardware often enough to detect changes with my limited usage
these days.

A while back, one of your users alerted my that the "my" command syntax had
changed on the recent firmware. I pushed a commit into my repo with the
proposed fixes, but still haven't received confirmation that the updated
app (not yet released to play store) works as intended with recent
firmware.

To be honest, my use cases with these devices is small these days. When I
do fire up my Chameleon it's for portable use of the revg hardware which I
have used to play with the door reader hardware and my school id. I would
like to see more Reve device users as well. Personally, I'm still waiting
for a solid working standard release of firmware that supports the common
desfire tags. Until that happens, my software efforts are limited to the
academic realm for now.

Sorry for posting this request out of place in the issues queue.

**Pull request merged**
