### PR TITLE
Crypto1 improved performance. Fixed nested authentication for Android

### PR DESCRIPTION
**Pull request by McEloff**
1. Crypto1 implemented from official repo, that improved performance up 30% (see issue #100)
2. Mifare classic nested authentication for Android fixed

### CODE REVIEW

**Comment by iceman1001** [comment]
This is that we swapped from old crypto1 implementation because it was too slow.
we got iskuris asm version,   since its has kind of small memory footprint.
We didnt use the new crypto1 implementation from offical chameleon mini repo because of size.
If this is the version from RevG repo,  it fits on that hardware.    The hardware on RevE is smaller.  Smaller MCU.
We would need some serious testing to see that everything was and that this doesnt break.

@bogiton   ??

**Comment by bogiton** [comment]
We could create a new branch for it and test it out separately.

**Comment by fmauNeko** [comment]
I built master with this applied, and enabled all configs, it fits on the device and works fine with MCT and 2 other hardware readers (a vending machine and a door lock).
I can do some more testing with an ACR122U and libnfc/mfoc.

**Comment by iceman1001** [comment]
ok,  I am ok with merging.  @bogiton ?   I have no time to test.

**Comment by bogiton** [comment]
I actually tested it yesterday! I had issues with the MCT app, losing the connection quite frequently, same as everyone I suppose. TagInfo identified the emulated tag normally. The actual real reader didn't respond at all. I wanted to sniff the communication between the reader and the Chameleon to maybe figure out what went wrong, but didn't get the chance.
One thing I noticed was that when the Chameleon was connected via USB (and powered by it) the MCT app was responding a bit better. Most issues were occurring when on battery.
It definitely needs more testing.

**Comment by bogiton** [comment]
@fmauNeko Some questions:
- What type of MFC did you emulate successfully? 1k or 4k?
- Were you also holding the power button when you presented the Chameleon to the real readers?
- What about the distances between them?

**Comment by fmauNeko** [comment]
@bogiton 

- 1k and 1k 7B. I could try 4k with my ACR122U tho.
- I didn't press the power button, the Chameleon starts correctly.
- Actually pressing the chameleon on the reader case so I guess pretty close, but that's how I use the tags anyway

**Comment by McEloff** [comment]
ACR122U with 7-bytes UID Classic tags uses full-byte anticollision frame during selection procedure. It is not supported by Chameleon. You can cherry-pick  c8cc99f7 commit from my repo, that fixed this selection method

**Comment by iceman1001** [comment]
@McEloff    Do a PR for that anti collision ?

**Comment by McEloff** [comment]
> @McEloff Do a PR for that anti collision ?

OK

**Comment by bogiton** [comment]
Weird. I was trying a 4b 1K as well. Might test it again tomorrow.

**Comment by iceman1001** [comment]
With the full frame anti collision implemented ,   you can test again @bogiton !

**Comment by bogiton** [comment]
Maybe MCT did behave a biiiit better now. But the real reader, again, didn't respond at all.
I think I'll have to do the rest of the tests, as you suggested; our current firmware without this patch and the stock firmware too.

**Comment by iceman1001** [comment]
Sounds like this PR isn't ready for merging.   We need more conclusive tests

**Comment by securechicken** [comment]
It seems like #100 is now a little bit more positive on this - probably more for the nested authentication fix with Android.
I feel like fixing memory-related bugs before might make the performance and/or fitness of this branch more clear.

**Comment by securechicken** [comment]
@McEloff , @iceman1001 , @bogiton 
To me it's a go with full throttle.
In order to test this patch, I merged it with a branch in sync with current master (where PR #110 and #107 are now applied, that I wanted before attempting any test, as I am convinced a lot of issues we have with Mifare are due to memory overlaps and corruptions).

I tested a 1k 4bytes dumb application (which only reads a sole sector), and 3 applications on a 4k 4bytes multi-purpose dump, as well as with MCT on Android (2 phones), SCL reader, and Proxmark3.
- the 1k and 4k are now read correctly with MCT. It never happened before,
- no regression on 1k application, it has always worked well,
- most importantly, 2 out of 3 applications I tested with the 4k and which were never working before are now working correctly, on 3 different real-life readers. It never happened before this patch (#110 and #107 fixed memory corruptions, which made the 4k readable, but doors did not open and drinks were not flowing free on vending machines :)),
- 1k and 4k headers are still recognized correctly on Proxmark3 and SCL with libnfc.

One of the 4k applications I test is still not responsive (a door lock), but this has nothing to do with this patch as it never worked with Chameleon-Mini (this only means we may still have a thing to patch elsewhere with authentication and/or 4k).

**Comment by iceman1001** [comment]
Great work @McEloff !
Great testing @shinhub !
I just merge this one and lets see what kinds of bugs we have now left.

**Pull request merged**
