### PR TITLE
Crypto1 Optimisations

### PR DESCRIPTION
**Pull request by Iskuri**
Hi All, here's my initial pull request for my crypto1 optimisations. This is based heavily on my previous work in this area so should be helpful at speeding things up. This involved converting a lot of my old ASM functions over and adapting some of the C code to work with it. Let me know if any extra comments are required or any formatting changes.

NB: this will need testing on a Chameleon Mini device before merging as mine unfortunately stopped working last night during testing. I used a test harness and simavr to develop and debug this code to make sure each of the functions matched the output of the original code, so if someone could give it a go that would be great. Thanks.

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice!  Really Nice!

@bogiton   Go Go Go!

**Comment by iceman1001** [comment]
@Iskuri  Remove the *.eep file from this PR.

**Comment by Iskuri** [comment]
Done.

**Comment by iceman1001** [comment]
I downloaded your fork / branch for this PR, and I can't get it to compile.

It complain about some part.

image

**Comment by iceman1001** [comment]
I downloaded your fork / branch for this PR,  and I cant get it to compile.

see below
image

**Comment by iceman1001** [comment]
hm.. ok,  added the asm file to the cproject file and it compiles

**Comment by Iskuri** [comment]
Yeah the asm file needs to be included, I didn't think of Visual Studio being a problem as I was only using GCC, are those the only two work environments for the code?

**Comment by iceman1001** [comment]
It wasnt either. I justed added the file and it compiles :)   My initial test looks great!

**Comment by Iskuri** [comment]
Glad to hear it! Let me know if it's sufficient for everyone's needs, there's more optimisation I can do but overdoing it can make it a bit obtuse to understand.

**Comment by iceman1001** [comment]
Awesome work!
I have test it and it works.   Havn't timed it either...

**Comment by Iskuri** [comment]
Thanks! I hope it's helpful for you guys.

**Pull request merged**
