### PR TITLE
LUFA 170418, avr-gcc 8 compat, USB name change, junk files clean

### PR DESCRIPTION
**Pull request by securechicken**
See https://github.com/iceman1001/ChameleonMini-rebooted/issues/89

### CODE REVIEW

**Comment by iceman1001** [comment]
Aouch..  that is a large one.  With changes that messes up current usb enumeration.
No to mention changed code styles.

**Comment by securechicken** [comment]
Agree, would rather do several ones, and not even sure updating LUFA is necessary (this is what causes so much changes). That's the result of being new to git, and not touching to any CPP source for more than 10 years :)
I will try to change that, but what do you mean by "messes up current usb enumeration" (is this about USB device ID, and a flag that might be missing, or are there more?), and "changing code style" (there have only been trailing white spaces deletion; my text editor automatically done that).

**Comment by iceman1001** [comment]
I guess they changed their style inside LUFA..
I noticed the vid/pid changed in LUFA.  Need to keep track of that, some other guis /app uses this to identify the mini and its different modes.  Might aswell change name etc in order to make the device identify as chameleon mini.  

I suspect the LUFA needs to be updated sooner or later.  Its just a massiv code to identify potential breaks in all other dev-envs / OS.    

btw,  If its only trailing white space,  then its fine.  

I am glad you have done this effort!

**Comment by securechicken** [comment]
It indeed needed some tuning (putting the PID back, storing LUFA USB descriptors in FLASH instead of RAM, adding some flags back) for it to work well. Without tuning, flashing went fine and device worked, but USB communication in non boot loader did not work anymore.
As for the styling, nothing has been changed from original LUFA style, instead trailing spaces removal (can check that by opting for "hide whitespace blabla" in diff options here).
I also tried to compile on Kali latest with avr-gcc 5.4 and it worked.
I flashed the resulting firmware (from OSX compilation) into the RevE, and tested some slots config, dumps load, and simulation against a reader. Did config with GUI Rebooted. Everything worked fine out of box.

**Comment by maxieds** [comment]
For what it's worth I had to update LUFA to the latest version locally to
do some custom mods to the RevG firmware too. This doesn't seem out of
place to me here either.

**Comment by iceman1001** [comment]
@bogiton   You tried this one?  Otherwise I will merge it tomorrow.

**Comment by bogiton** [comment]
I will check it out later tonight. Basically, if it compiles ok with Atmel Studio. Seems like a useful PR.

**Comment by bogiton** [comment]
Ok, it seems to be fine. Compiles normally from Atmel Studio as well and it works fine with the latest GUI too.

**Pull request merged**
