### PR TITLE
Modification in log mode

### PR DESCRIPTION
**Pull request by MageDelfador**

### CODE REVIEW

**Comment by iceman1001** [comment]
So how do you handle wupa/halt situation now?

**Comment by MageDelfador** [comment]
original code is redundant.It will return one more NO_RESPONSE when auth failed.
Some readers expect auth failed before second auth.One more NO_RESPONSE will case reader never go to second auth

**Comment by iceman1001** [comment]
WUPA/HALT has nothing to do with AUTH.   Would you mind explaining it for real the purpose of the fix?

**Comment by MageDelfador** [comment]
Sorry,I copied wrong code.
My English is not good,I try my best to explain it.
original code will running when receive reader's REQA/WUPA.It determines whether to return NO_RESPONSE according to the current status of the card.But it is redundant.It can cause errors in some cases.For example, I mentioned earlier,if reader expect an auth failed before second auth,reader will send REQA/WUPA after first auth failed.but original code let reader receive one more NO_RESPONSE.It will reset reader's status and never go to second auth.

**Comment by iceman1001** [comment]
The implementation tries to mimic the iso14443a-3,    and you are describing readers who doesn't seem to follow standard.

**Comment by MageDelfador** [comment]
I read iso14443 and found no problem with the code. But all my cards can pass the reader, except the chameleon. So I retested it again. I found that if I don't press the power button of the chameleon to get close to the reader, it can work normally. I think the reason is that the reader disconnected the power of the card to reset the card after completing the first authentication. I recommend modifying this code only in log mode, because log mode requires continuous power supply, and this modification will have no other impact.After all, chameleon logs are used to analyze readers' behavior, not protocols.

**Pull request closed without merging**
