### PR TITLE
fix MifareClassicAppLog bug

### PR DESCRIPTION
**Pull request by MageDelfador**

### CODE REVIEW

**Comment by iceman1001** [comment]
Interesting PR,
however I get the feeling that it contains several different fixes.
I suggest you divide them up and make separate PR's in order to keep it easier to see what each PR fixes.

**Comment by iceman1001** [comment]
So what does this fix do?

**Comment by MageDelfador** [comment]
fix bug

**Comment by iceman1001** [comment]
Not a very productive answer.

**Comment by MageDelfador** [comment]
Only two lines changed,bug is obvious. I dont know how to explain. Line 437 is a logical bug.Line 996 not consider iso14443a_ APP_ CUSTOM_ PARITY in retSize. MifareClassicAppLog write wrong logs before this commit.

**Comment by iceman1001** [comment]
Ok, I see.  The retSize has a dual meaning.   Good catch!

**Pull request merged**
