### PR TITLE
Add UIDMODE command

### PR DESCRIPTION
**Pull request by ca1e**
Add UIDMODE command to chang magic uid mode

### CODE REVIEW

**Comment by iceman1001** [comment]
Thank you for your contribution to the code.
I see that you have mixed up several different changes in one PR.
May I suggest you divide it up into several different PR targeted to specific changes.  Like one for UIDMODE,  one for NTAG etc.

**Comment by ca1e** [comment]
yes and sure.I can merge the UIDMODE change only,and rebase the ntag215 support for a new PR.

**Comment by ca1e** [comment]
Hi iceman, I just divide it up into different PR and have tested  to be sure there is no any conflicts to merge both.thank you! 
I'd like to contribute to it and try my best

**Comment by iceman1001** [comment]
Thanks,   the main reason for asking is to find easily which PR that introduced a certain functionality or change.
When things changes multiple things at once,  its becomes harder to find potential bugs / errors.

**Comment by iceman1001** [comment]
nice and easy to follow.
The question now since you enabled it by default,  if the firmware gets too large.   We were on the border before.

**Pull request merged**
