### PR TITLE
make mifare log printable

### PR DESCRIPTION
**Pull request by MageDelfador**

### CODE REVIEW

**Comment by iceman1001** [comment]
that 1500 byte array sounds like a large one.

**Comment by MageDelfador** [comment]
yes,but large array is necessary for log.writing flash is slow

**Comment by iceman1001** [comment]
Maybe, be then we don't have much resources in Chameleon.

**Comment by MageDelfador** [comment]
1500 array size works well with this setting:
```
#Supported configurations
#WARNING. If you flash from Windows original tools, choose either CLASSIC OR ULTRALIGHT
#BOTH will produce a firmware that is too big for BOOT_LOADER_EXE to handle
SETTINGS	+= -DCONFIG_MF_CLASSIC_SUPPORT
#SETTINGS	+= -DCONFIG_MF_ULTRALIGHT_SUPPORT
#SETTINGS	+= -DCONFIG_NTAG213_SUPPORT
#SETTINGS	+= -DCONFIG_NTAG215_SUPPORT
#SETTINGS	+= -DCONFIG_NTAG216_SUPPORT
SETTINGS	+= -DCONFIG_MF_CLASSIC_DETECTION_SUPPORT
SETTINGS	+= -DCONFIG_MF_CLASSIC_BRUTE_SUPPORT
SETTINGS	+= -DCONFIG_MF_CLASSIC_LOG_SUPPORT

#Support magic mode on mifare classic configuration
# SETTINGS	+= -DSUPPORT_MF_CLASSIC_MAGIC_MODE

#Support activating firmware upgrade mode through command-line
SETTINGS	+= -DSUPPORT_FIRMWARE_UPGRADE

#Enable the MEMORYTEST and/or MEMORYINFO commands to help with memory management debug
#REQUIRES enabling CONFIG_MF_CLASSIC_SUPPORT and CONFIG_MF_CLASSIC_DETECTION_SUPPORT
#SETTINGS    += -DCONFIG_DEBUG_MEMORYTEST_COMMAND
#SETTINGS    += -DCONFIG_DEBUG_MEMORYINFO_COMMAND
```
I'm sure even original code can't work with 128 size array,it will lost lots of logs.

**Comment by iceman1001** [comment]
The log is suppose to write once with every response.   So I don't understand why you are adding a longer line?  Sounds more like the logbuffer should be emptied with every write. 

I am sure you can bring clarity in this for me

**Comment by MageDelfador** [comment]
Writing flash is very slow. Additional writing flash in the middle of communication will cause card response timeout.Therefore, the log can only be cached.

**Pull request closed without merging**
